# Generated by Django 2.2.7 on 2021-02-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'EMP_INFO',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('empref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adrref', to='funcbaseview.Employee')),
            ],
            options={
                'db_table': 'ADR_INFO',
            },
        ),
    ]
